### ISSUE TITLE
启动后没有反应

### ISSUE THREAD

**Issue by RimuruChan** [UltimateLeaks/JByteMod-Reborn#1]
只在后台有进程，没有窗口

**Comment by DotRacel** [comment]
有没有有什么错误

**Comment by RimuruChan** [comment]
[02:27:23] [INFO] Reading Language XML..
[02:27:23] [INFO] Successfully loaded 214 local resources and 214 default resources
[02:27:24] [INFO] Unicode check finished!
[02:27:24] [WARN] Property File "jbytemod.cfg" does not exist, creating...
[02:27:24] [INFO] Prop file doesn't exist, creating.
[02:27:25] [INFO] Setting default Look and Feel
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/bukkit/scheduler/BukkitRunnable
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at me.grax.jbytemod.plugin.PluginManager.loadPlugins(PluginManager.java:53)
        at me.grax.jbytemod.plugin.PluginManager.<init>(PluginManager.java:22)
        at me.grax.jbytemod.JByteMod.setVisible(JByteMod.java:473)
        at me.grax.jbytemod.JByteMod$2.run(JByteMod.java:228)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.bukkit.scheduler.BukkitRunnable
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 32 more
[02:27:49] [INFO] Discord is now ready.

我佛了，跟bukkit有啥关系

**Comment by DotRacel** [comment]
你JByteMod插件里加Bukkit插件？

**Comment by RimuruChan** [comment]
没有啊，启动的报错
报错其中一行
> Caused by: java.lang.ClassNotFoundException: org.bukkit.scheduler.BukkitRunnable

**Comment by DotRacel** [comment]
plugin 文件夹内不要放东西。
