### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by ghost** [UltimateLeaks/JByteMod-Reborn#2]
PS C:\Users\\*\*\*\*\*\Desktop> java -jar .\JByteMod-Reborn-v1.8.jar
[14:36:19] [INFO] Reading Language XML..
[14:36:19] [INFO] Successfully loaded 215 local resources and 215 default resources
[14:36:19] [INFO] Unicode check finished!
[14:36:19] [WARN] Property File "jbytemod.cfg" does not exist, creating...
[14:36:19] [INFO] Prop file doesn't exist, creating.
[14:36:19] [INFO] Setting default Look and Feel
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at me.grax.jbytemod.plugin.PluginManager.loadPlugins(PluginManager.java:53)
        at me.grax.jbytemod.plugin.PluginManager.<init>(PluginManager.java:22)
        at me.grax.jbytemod.JByteMod.setVisible(JByteMod.java:473)
        at me.grax.jbytemod.JByteMod$2.run(JByteMod.java:228)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 32 more

**Comment by DotRacel** [comment]
What did you do? Can you send the sample of this file?

**Comment by ghost** [comment]
Nvm, this problem happen only when i store my plugins i want to crack in `{JByteMod-Path}\plugins`.
I think JByteMod is trying to load plugins in put in this dir as a JByteMod plugin.
