### ISSUE TITLE
Can't find python on linux even if I set my path

### ISSUE THREAD

**Issue by 5HT2** [UltimateLeaks/JByteMod-Reborn#4]
I tried the default python bin (`3.8.1`)and tried setting my path to `2.7.17`, I get the same error

```
java.io.IOException: Cannot run program "py": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:621)
	at java.lang.Runtime.exec(Runtime.java:451)
	at java.lang.Runtime.exec(Runtime.java:348)
	at me.grax.jbytemod.decompiler.KrakatauDecompiler.decompile(KrakatauDecompiler.java:63)
	at me.grax.jbytemod.decompiler.Decompiler.decompile(Decompiler.java:59)
	at me.grax.jbytemod.decompiler.Decompiler.run(Decompiler.java:44)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 more


Please try setting the python path
```

![2020-03-19-122905_404x114_scrot](https://user-images.githubusercontent.com/17222512/77090239-3e2c4900-69dd-11ea-96b5-e9712c309c07.png)
![2020-03-19-122929_556x184_scrot](https://user-images.githubusercontent.com/17222512/77090277-497f7480-69dd-11ea-8485-fc6bc7716dc5.png)

**Comment by foaw** [comment]
This is a [JByteMod bug](https://github.com/GraxCode/JByteMod-Beta/issues/43#issuecomment-387820616). Try to add a space at the end of the path.

**Comment by 5HT2** [comment]
A space where? My path looks like `PATH='~/bin:/other/paths:$PATH`

**Comment by 5HT2** [comment]
Oh, I see. I'll try recompiling and see if it fixes it.

**Comment by fee1-dead** [comment]
Try setting your `python_path` enviornment variable

**Comment by 5HT2** [comment]
It's set.

**Comment by fee1-dead** [comment]
is it set to `py `instead of `python`?

**Comment by 5HT2** [comment]
Nope, I've tried that as well.
