### ISSUE TITLE
Have no idea what this is.

### ISSUE THREAD

**Issue by harmlessc** [UltimateLeaks/JByteMod-Reborn#6]
java.io.IOException: Access is denied
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at me.grax.jbytemod.res.Options.lambda$save$1(Options.java:120)
	at java.lang.Thread.run(Unknown Source)

Please report exceptions on github.

https://github.com/GraxCode/JByteMod-Beta

Please help me with this. Whenever I try to open a jar, the memory fills up for some reason.

**Comment by fee1-dead** [comment]
https://stackoverflow.com/questions/37105012/execute-jar-file-as-administrator-in-windows
